version: '2.4'
services:
  db:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    
  app:
    env_file: .env

  web:
    volumes:
      - graphiql:/public-console:ro

  graphql-engine:
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/pokeapi"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"

  graphiql:
    image: pokeapi/graphiql:1.0.1
    command: sh -c 'cp -a /app/static/. /transfer/ && tail -f /etc/passwd'
    volumes:
      - graphiql:/transfer
    depends_on: 
      - graphql-engine

volumes: 
  graphiql:

# docker-compose -f docker-compose.yml -f Resources/compose/docker-compose-graphql.yml up
