# This query searches for pokemon having a german name like "Ento.*"
# Should return Psyduck and Golduck

query searchForPokemonInGerman {
  pokemonspecies(
    where: {
      pokemonspeciesnames: {
        language: { name: { _eq: "de" } }
        name: { _regex: "Ento.*" }
      }
    }
  ) {
    pokemonspeciesnames(
      where: { language: { name: { _eq: "de" } } }
    ) {
      name
    }
    id
  }
}
