apiVersion: batch/v1
kind: Job
metadata:
  name: load-graphql
spec:
  template:
    spec:
      containers:
        - name: load-graphql
          command: ["sh", "-c"]
          args:
            - apt-get update && apt-get install -y curl &&
              curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=v2.48.1 bash &&
              hasura md apply --endpoint http://graphql:8080 --project /code/pokeapi/graphql/v1beta2 --admin-secret $(HASURA_GRAPHQL_ADMIN_SECRET)
          volumeMounts:
            - mountPath: /code/pokeapi/graphql/v1beta2/
              name: graphql-share
      volumes:
        - name: graphql-share
          hostPath:
            path: /code/pokeapi/graphql/v1beta2/
