# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0001_squashed_0006_auto_20150910_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='generation',
            field=models.ForeignKey(related_name='ability', blank=True, to='pokemon_v2.Generation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='abilitychangedescription',
            name='language',
            field=models.ForeignKey(related_name='abilitychangedescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='abilitydescription',
            name='language',
            field=models.ForeignKey(related_name='abilitydescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='abilityflavortext',
            name='language',
            field=models.ForeignKey(related_name='abilityflavortext_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='abilityflavortext',
            name='version_group',
            field=models.ForeignKey(related_name='abilityflavortext', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='abilityname',
            name='language',
            field=models.ForeignKey(related_name='abilityname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='berryfirmnessname',
            name='language',
            field=models.ForeignKey(related_name='berryfirmnessname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='characteristicdescription',
            name='language',
            field=models.ForeignKey(related_name='characteristicdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contesteffectdescription',
            name='language',
            field=models.ForeignKey(related_name='contesteffectdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contesttypename',
            name='language',
            field=models.ForeignKey(related_name='contesttypename_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='egggroupname',
            name='language',
            field=models.ForeignKey(related_name='egggroupname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='encounter',
            name='version',
            field=models.ForeignKey(related_name='encounter', blank=True, to='pokemon_v2.Version', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='encounterconditionname',
            name='language',
            field=models.ForeignKey(related_name='encounterconditionname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='encounterconditionvaluename',
            name='language',
            field=models.ForeignKey(related_name='encounterconditionvaluename_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='encountermethodname',
            name='language',
            field=models.ForeignKey(related_name='encountermethodname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='encounterslot',
            name='version_group',
            field=models.ForeignKey(related_name='encounterslot', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='evolutiontriggername',
            name='language',
            field=models.ForeignKey(related_name='evolutiontriggername_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='generation',
            name='region',
            field=models.ForeignKey(related_name='generation', blank=True, to='pokemon_v2.Region', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='generationname',
            name='generation',
            field=models.ForeignKey(related_name='generationname', blank=True, to='pokemon_v2.Generation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='generationname',
            name='language',
            field=models.ForeignKey(related_name='generationname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='growthratedescription',
            name='language',
            field=models.ForeignKey(related_name='growthratedescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='itemcategoryname',
            name='language',
            field=models.ForeignKey(related_name='itemcategoryname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='itemdescription',
            name='language',
            field=models.ForeignKey(related_name='itemdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='itemflagdescription',
            name='language',
            field=models.ForeignKey(related_name='itemflagdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='itemflavortext',
            name='language',
            field=models.ForeignKey(related_name='itemflavortext_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='itemflavortext',
            name='version_group',
            field=models.ForeignKey(related_name='itemflavortext', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='itemflingeffectdescription',
            name='language',
            field=models.ForeignKey(related_name='itemflingeffectdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='itemgameindex',
            name='generation',
            field=models.ForeignKey(related_name='itemgameindex', blank=True, to='pokemon_v2.Generation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='itemname',
            name='language',
            field=models.ForeignKey(related_name='itemname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='itempocketname',
            name='language',
            field=models.ForeignKey(related_name='itempocketname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='languagename',
            name='language',
            field=models.ForeignKey(related_name='languagename_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(related_name='location', blank=True, to='pokemon_v2.Region', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='locationareaencounterrate',
            name='version',
            field=models.ForeignKey(related_name='locationareaencounterrate', blank=True, to='pokemon_v2.Version', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='locationareaname',
            name='language',
            field=models.ForeignKey(related_name='locationareaname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='locationgameindex',
            name='generation',
            field=models.ForeignKey(related_name='locationgameindex', blank=True, to='pokemon_v2.Generation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='locationname',
            name='language',
            field=models.ForeignKey(related_name='locationname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='move',
            name='generation',
            field=models.ForeignKey(related_name='move', blank=True, to='pokemon_v2.Generation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='move',
            name='type',
            field=models.ForeignKey(related_name='move', blank=True, to='pokemon_v2.Type', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='movebattlestylename',
            name='language',
            field=models.ForeignKey(related_name='movebattlestylename_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='movechange',
            name='type',
            field=models.ForeignKey(related_name='movechange', blank=True, to='pokemon_v2.Type', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='movechange',
            name='version_group',
            field=models.ForeignKey(related_name='movechange', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='movedamageclassdescription',
            name='language',
            field=models.ForeignKey(related_name='movedamageclassdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='moveeffectchange',
            name='version_group',
            field=models.ForeignKey(related_name='moveeffectchange', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='moveeffectchangedescription',
            name='language',
            field=models.ForeignKey(related_name='moveeffectchangedescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='moveeffectdescription',
            name='language',
            field=models.ForeignKey(related_name='moveeffectdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='moveflagdescription',
            name='language',
            field=models.ForeignKey(related_name='moveflagdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='moveflavortext',
            name='language',
            field=models.ForeignKey(related_name='moveflavortext_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='moveflavortext',
            name='version_group',
            field=models.ForeignKey(related_name='moveflavortext', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='movemetaailmentname',
            name='language',
            field=models.ForeignKey(related_name='movemetaailmentname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='movemetacategorydescription',
            name='language',
            field=models.ForeignKey(related_name='movemetacategorydescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='movename',
            name='language',
            field=models.ForeignKey(related_name='movename_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='movetargetdescription',
            name='language',
            field=models.ForeignKey(related_name='movetargetdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='naturename',
            name='language',
            field=models.ForeignKey(related_name='naturename_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='palparkareaname',
            name='language',
            field=models.ForeignKey(related_name='palparkareaname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokeathlonstatname',
            name='language',
            field=models.ForeignKey(related_name='pokeathlonstatname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='region',
            field=models.ForeignKey(related_name='pokedex', blank=True, to='pokemon_v2.Region', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokedexdescription',
            name='language',
            field=models.ForeignKey(related_name='pokedexdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokedexversiongroup',
            name='version_group',
            field=models.ForeignKey(related_name='pokedexversiongroup', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemoncolorname',
            name='language',
            field=models.ForeignKey(related_name='pokemoncolorname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonformgeneration',
            name='generation',
            field=models.ForeignKey(related_name='pokemonformgeneration', blank=True, to='pokemon_v2.Generation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonformname',
            name='language',
            field=models.ForeignKey(related_name='pokemonformname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemongameindex',
            name='version',
            field=models.ForeignKey(related_name='pokemongameindex', blank=True, to='pokemon_v2.Version', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonhabitatname',
            name='language',
            field=models.ForeignKey(related_name='pokemonhabitatname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonitem',
            name='version',
            field=models.ForeignKey(related_name='pokemonitem', blank=True, to='pokemon_v2.Version', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='version_group',
            field=models.ForeignKey(related_name='pokemonmove', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonmovemethodname',
            name='language',
            field=models.ForeignKey(related_name='pokemonmovemethodname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonshapename',
            name='language',
            field=models.ForeignKey(related_name='pokemonshapename_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='generation',
            field=models.ForeignKey(related_name='pokemonspecies', blank=True, to='pokemon_v2.Generation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonspeciesdescription',
            name='language',
            field=models.ForeignKey(related_name='pokemonspeciesdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonspeciesflavortext',
            name='language',
            field=models.ForeignKey(related_name='pokemonspeciesflavortext_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonspeciesflavortext',
            name='version',
            field=models.ForeignKey(related_name='pokemonspeciesflavortext', blank=True, to='pokemon_v2.Version', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonspeciesname',
            name='language',
            field=models.ForeignKey(related_name='pokemonspeciesname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='type',
            field=models.ForeignKey(related_name='pokemontype', blank=True, to='pokemon_v2.Type', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='regionname',
            name='language',
            field=models.ForeignKey(related_name='regionname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='regionname',
            name='region',
            field=models.ForeignKey(related_name='regionname', blank=True, to='pokemon_v2.Region', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statname',
            name='language',
            field=models.ForeignKey(related_name='statname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='supercontesteffectdescription',
            name='language',
            field=models.ForeignKey(related_name='supercontesteffectdescription_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='type',
            name='generation',
            field=models.ForeignKey(related_name='type', blank=True, to='pokemon_v2.Generation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='typeefficacy',
            name='damage_type_id',
            field=models.ForeignKey(related_name='damage_type', blank=True, to='pokemon_v2.Type', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='typeefficacy',
            name='target_type_id',
            field=models.ForeignKey(related_name='target_type', blank=True, to='pokemon_v2.Type', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='typegameindex',
            name='generation',
            field=models.ForeignKey(related_name='typegameindex', blank=True, to='pokemon_v2.Generation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='typegameindex',
            name='type',
            field=models.ForeignKey(related_name='typegameindex', blank=True, to='pokemon_v2.Type', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='typename',
            name='language',
            field=models.ForeignKey(related_name='typename_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='typename',
            name='type',
            field=models.ForeignKey(related_name='typename', blank=True, to='pokemon_v2.Type', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='version',
            name='version_group',
            field=models.ForeignKey(related_name='version', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='versiongroup',
            name='generation',
            field=models.ForeignKey(related_name='versiongroup', blank=True, to='pokemon_v2.Generation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='versiongrouppokemonmovemethod',
            name='version_group',
            field=models.ForeignKey(related_name='versiongrouppokemonmovemethod', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='versiongroupregion',
            name='region',
            field=models.ForeignKey(related_name='versiongroupregion', blank=True, to='pokemon_v2.Region', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='versiongroupregion',
            name='version_group',
            field=models.ForeignKey(related_name='versiongroupregion', blank=True, to='pokemon_v2.VersionGroup', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='versionname',
            name='language',
            field=models.ForeignKey(related_name='versionname_language', blank=True, to='pokemon_v2.Language', null=True),
            preserve_default=True,
        ),
    ]
