from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0002_itemsprites_pokemonformsprites_pokemonsprites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ability",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="abilityname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="berry",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="berryfirmness",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="berryfirmnessname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="berryflavor",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="berryflavorname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="contesttype",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="contesttypename",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="egggroup",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="egggroupname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="encountercondition",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="encounterconditionname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="encounterconditionvalue",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="encounterconditionvaluename",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="encountermethod",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="encountermethodname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="evolutiontrigger",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="evolutiontriggername",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="gender",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="generation",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="generationname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="growthrate",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="itemattribute",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="itemattributename",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="itemcategory",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="itemcategoryname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="itemflingeffect",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="itemname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="itempocket",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="itempocketname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="languagename",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="locationarea",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="locationareaname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="locationname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="move",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="moveattribute",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="moveattributename",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movebattlestyle",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movebattlestylename",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movedamageclass",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movedamageclassname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movelearnmethod",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movelearnmethodname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movemetaailment",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movemetaailmentname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movemetacategory",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movename",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movetarget",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="movetargetname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="nature",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="naturename",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="palparkarea",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="palparkareaname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokeathlonstat",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokeathlonstatname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokedex",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokedexname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemoncolor",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemoncolorname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemonform",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemonformname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemonhabitat",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemonhabitatname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemonshape",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemonshapename",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemonspecies",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="pokemonspeciesname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="regionname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="stat",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="statname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="typename",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="version",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="versiongroup",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="versionname",
            name="name",
            field=models.CharField(max_length=100, db_index=True),
            preserve_default=True,
        ),
    ]
