# Generated by Django 2.1.11 on 2020-04-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0004_iso639length_20191217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonFormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('pokemon_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemonformtype', to='pokemon_v2.PokemonForm')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemonformtype', to='pokemon_v2.Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
