# Generated by Django 2.1.11 on 2020-07-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0006_auto_20200725_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='base_happiness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='capture_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='gender_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='hatch_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
