# Generated by Django 2.1.11 on 2021-02-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0008_auto_20201123_2045"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonTypePast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.IntegerField()),
                (
                    "generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemontypepast",
                        to="pokemon_v2.Generation",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemontypepast",
                        to="pokemon_v2.Pokemon",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemontypepast",
                        to="pokemon_v2.Type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
