# Generated by Django 2.1.15 on 2023-11-19 03:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0013_pokemonabilitypast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonsprites",
            name="sprites",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
