# Generated by Django 3.1.14 on 2023-11-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0014_auto_20231119_0303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonsprites",
            name="sprites",
            field=models.JSONField(),
        ),
    ]
