# Generated by Django 3.1.14 on 2023-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0015_auto_20231121_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemsprites",
            name="sprites",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="pokemonformsprites",
            name="sprites",
            field=models.JSONField(),
        ),
    ]
