# Generated by Django 3.2.23 on 2024-03-26 20:49

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0015_pokemoncries'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together={('machine_number', 'version_group')},
        ),
        migrations.CreateModel(
            name='MachineVersionLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.IntegerField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineversionlocations', to='pokemon_v2.location')),
                ('location_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineversionlocations', to='pokemon_v2.locationarea')),
                ('machine', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='pokemon_v2.machine', to_fields={'machine_number': compositefk.fields.LocalFieldValue('machine_number'), 'version_group': compositefk.fields.LocalFieldValue('version_group')})),
                ('version_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machineversionlocations', to='pokemon_v2.versiongroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='location_areas',
            field=models.ManyToManyField(blank=True, through='pokemon_v2.MachineVersionLocations', to='pokemon_v2.LocationArea'),
        ),
        migrations.AddField(
            model_name='machine',
            name='locations',
            field=models.ManyToManyField(blank=True, through='pokemon_v2.MachineVersionLocations', to='pokemon_v2.Location'),
        ),
    ]
