# Generated by Django 3.2.23 on 2024-04-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0018_alter_honeytrees_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeytrees',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
