# Generated by Django 3.2.25 on 2025-09-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0018_auto_20250123_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemonsummary_language', to='pokemon_v2.language')),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemonsummary', to='pokemon_v2.pokemon')),
            ],
            options={
                'unique_together': {('pokemon', 'language')},
            },
        ),
    ]
