# Generated by Django 3.2.25 on 2025-09-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0018_auto_20250123_1838"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemondexnumber",
            name="pokemon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name="pokemondexnumber",
                to="pokemon_v2.pokemon",
            ),
        ),
    ]
