# Generated by Django 3.2.25 on 2026-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0022_pokemonevolution_min_damage_taken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteristicdescription",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="growthratedescription",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="itemattributedescription",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="moveattributedescription",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="movedamageclassdescription",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="movelearnmethoddescription",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="movemetacategorydescription",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="movetargetdescription",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="pokedexdescription",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="pokemonspeciesdescription",
            name="description",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
