# Generated by Django 5.2.10 on 2026-01-26 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_v2",
            "0024_alter_ability_generation_alter_abilitychange_ability_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonStatPast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_stat", models.IntegerField()),
                ("effort", models.IntegerField()),
                (
                    "generation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.generation",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.pokemon",
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.stat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
