# Generated by Django 5.2.10 on 2026-02-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0025_pokemonstatpast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonevolution",
            name="base_form",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific form required for evolution (null = any form)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_form_evolutions",
                to="pokemon_v2.pokemon",
            ),
        ),
    ]
