# Generated by Django 4.2.27 on 2026-01-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0025_pokemonstatpast"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonStatOriginal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_stat", models.IntegerField()),
                (
                    "pokemon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.pokemon",
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.stat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
