# Generated by Django 5.2.10 on 2026-03-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0025_pokemonstatpast"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_purchasable", models.BooleanField()),
                ("purchase_price", models.IntegerField()),
                ("sell_price", models.IntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.item",
                    ),
                ),
                (
                    "version_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.versiongroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
