# Generated by Django 5.2.10 on 2026-06-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0026_alter_pokemonevolution_base_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonevolution",
            name="near_special_rock",
            field=models.BooleanField(default=False),
        ),
    ]
