# Generated by Django 5.2.10 on 2026-04-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0026_itemmechaniccontext_itemmechaniceffecttype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmechanic",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemonspecies",
            name="is_ultra_beast",
            field=models.BooleanField(default=False),
        ),
    ]
