# Generated by Django 5.2.10 on 2026-06-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0027_pokemonevolution_near_special_rock"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonevolution",
            name="evolved_form",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific form of the evolved species",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evolved_form",
                to="pokemon_v2.pokemon",
            ),
        ),
        migrations.AddField(
            model_name="pokemonevolution",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pokemonevolution",
            name="version_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_group",
                to="pokemon_v2.versiongroup",
            ),
        ),
    ]
