# Generated by Django 5.2.10 on 2026-06-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0028_pokemonevolution_evolved_form_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berry",
            name="growth_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="berry",
            name="max_harvest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="berry",
            name="natural_gift_power",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="berry",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="berry",
            name="smoothness",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="berry",
            name="soil_dryness",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
