# Generated by Django 5.2.10 on 2026-06-30 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0029_pokemonformmethod_pokemonformcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonformcondition',
            name='move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_v2.move'),
        ),
    ]
