# Generated by Django 5.2.10 on 2026-04-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0029_remove_itemmechaniccondition_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmechaniceffect',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
