# Generated by Django 5.2.10 on 2026-07-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0030_alter_berry_growth_time_alter_berry_max_harvest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncounterPokemonDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_perfect_ivs", models.IntegerField(blank=True, null=True)),
                ("always_shiny", models.BooleanField(default=False)),
                ("never_shiny", models.BooleanField(default=False)),
                ("is_alpha", models.BooleanField(default=False)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemon_v2.encounter",
                    ),
                ),
            ],
        ),
    ]
