# Generated by Django 5.2.10 on 2026-04-09 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0031_logicoperatortype_mechanicconditiontype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmechaniccondition",
            name="condition_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="pokemon_v2.mechanicconditiontype",
            ),
        ),
        migrations.AlterField(
            model_name="itemmechaniccondition",
            name="logic_operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="pokemon_v2.logicoperatortype",
            ),
        ),
    ]
