# Generated by Django 5.2.10 on 2026-08-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0031_encounterpokemondetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonevolution",
            name="time_of_day",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
