# Generated by Django 5.2.10 on 2026-08-08 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0032_alter_pokemonevolution_time_of_day"),
        ("pokemon_v2", "0033_itemprice"),
    ]

    operations = []
