# Generated by Django 5.2.10 on 2026-08-08 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0034_merge_20260808_2052"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="cost",
        ),
    ]
