# Generated by Django 5.2.10 on 2026-08-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0035_pokemonformflavortext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemonevolution",
            name="base_form",
        ),
        migrations.RemoveField(
            model_name="pokemonevolution",
            name="evolved_form",
        ),
        migrations.AddField(
            model_name="pokemonevolution",
            name="condition_expression",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Evaluatable RPN condition expression using evolution variables (e.g. 'EC 100 % 0 ==')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pokemonevolution",
            name="needs_one_of_natures",
            field=models.IntegerField(
                blank=True,
                help_text="25-bit bitmask of allowed nature IDs (1 << (nature_id - 1))",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pokemonevolution",
            name="required_pokemon_form",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific form required for evolution (null = any form; e.g. burmy-plant, sinistea-antique)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_in_evolutions",
                to="pokemon_v2.pokemonform",
            ),
        ),
        migrations.AddField(
            model_name="pokemonevolution",
            name="evolved_pokemon_form",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific form resulting from evolution (null = default form; e.g. polteageist-antique, wormadam-sandy)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evolved_into_evolutions",
                to="pokemon_v2.pokemonform",
            ),
        ),
        migrations.CreateModel(
            name="EvolutionVariable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("symbol", models.CharField(max_length=10)),
                ("data_type", models.CharField(default="uint32", max_length=20)),
                (
                    "version_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.versiongroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvolutionVariableDescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(default="", max_length=2000)),
                (
                    "evolution_variable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.evolutionvariable",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_language",
                        to="pokemon_v2.language",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvolutionVariableName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "evolution_variable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.evolutionvariable",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_language",
                        to="pokemon_v2.language",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
