# Generated by Django 5.2.10 on 2026-09-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0036_pokemonevolution_condition_expression_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evolutionvariable",
            name="source",
            field=models.CharField(
                default="pokemon",
                help_text="Where the value comes from: 'pokemon' for data stored on the Pokemon (e.g. EC, PID), 'player-input' for an action taken by the player while evolving (e.g. SPIN_DIR, SPIN_SEC)",
                max_length=20,
            ),
        ),
    ]
