# Generated by Django 5.2.10 on 2026-10-07 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_v2", "0037_evolutionvariable_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonDexNumberVariety",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.IntegerField(blank=True, null=True)),
                (
                    "pokemon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.pokemon",
                    ),
                ),
                (
                    "pokemon_dex_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="pokemon_v2.pokemondexnumber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
